version: '3.9'

services:
  postgres-database:
    image: postgres:latest
    container_name: wakuwaku-postgres-container
    environment:
      POSTGRES_DB: wakuwaku
      POSTGRES_USER: wakuwaku
      POSTGRES_PASSWORD: wakuwaku
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wakuwaku-network

  
volumes:
  postgres_data:

networks:
  wakuwaku-network:
    driver: bridge